### ISSUE TITLE
Crashes when loading external image

### ISSUE THREAD

**Issue by tomwtsn** [birogeri/kspace-explorer#5]
Hi! This is an amazing tool. Unfortunately the programme is crashing when I try to load an external image, with the same result either by dragging-and-dropping or using the menu to open an image. What image formats is it intended to be compatible with?

This is the error given:

`Warning: file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Controls/ToolBar.qml:146:9: QML QQuickItem*: Binding loop detected for property "layoutHeight" (file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Controls/ToolBar.qml:146, file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Controls/ToolBar.qml)
Warning: file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:409:9: QML ToolBar: Binding loop detected for property "implicitHeight" (file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:409, file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml)
Warning: file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:409:9: QML ToolBar: Binding loop detected for property "implicitHeight" (file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:409, file:///Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml)
Warning: Model size of -25 is less than 0 (None:0, None)
Fatal: Traceback (most recent call last):
  File "kspace.py", line 604, in load_new_img
    self.execute_load()
  File "kspace.py", line 570, in execute_load
    im = ImageManipulators(self.file_data, self.is_image)
  File "kspace.py", line 99, in __init__
    self.np_fft(self.img, self.kspacedata)
  File "kspace.py", line 132, in np_fft
    out[:] = fftshift(fft2(ifftshift(img)))
  File "<__array_function__ internals>", line 180, in fft2
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/fft/_pocketfft.py", line 1014, in fft2
    return _raw_fftnd(a, s, axes, fft, norm)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/fft/_pocketfft.py", line 703, in _raw_fftnd
    s, axes = _cook_nd_args(a, s, axes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/fft/_pocketfft.py", line 688, in _cook_nd_args
    s = take(a.shape, axes)
  File "<__array_function__ internals>", line 180, in take
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
IndexError: index -2 is out of bounds for axis 0 with size 1 (None:0, None)
zsh: abort      python3 kspace.py`

**Comment by birogeri** [comment]
It should be compatible with most of the common 2D image formats and DICOM.
Is it a 3D DICOM you tried?

**Comment by tomwtsn** [comment]
A JPEG and a bitmap image. I’m going to update Python and try again.

**Comment by birogeri** [comment]
Those files should definitely work. Which numpy version is installed?
Did it work with any image at all?
Please let me know what happens after the update.

**Comment by tomwtsn** [comment]
DIdn't work after updating Python. I have numpy version 1.22.2.

It works great with the preloaded MR brain.

**Comment by birogeri** [comment]
I have published a new branch with basic logging.
Could you please try running this [version](https://github.com/birogeri/kspace-explorer/archive/logging.zip) and share `kspace.log` (you can do it here on [GitHub](https://gist.github.com/) or [pastebin](https://pastebin.com/))

**Comment by tomwtsn** [comment]
Here is [kspace.log](https://github.com/birogeri/kspace-explorer/files/8056190/kspace.log)

I'm not sure why it says the file doesn't exist because it definitely does.

**Comment by birogeri** [comment]
Thank you, this is helpful. 
I have pushed a bugfix birogeri@a60b5e42b637ff59b7e6f72516fb8b9dfb86ec17 so if you redownload the [logging version](https://github.com/birogeri/kspace-explorer/archive/logging.zip), it should now open files without a problem.
Please let me know if it behaves as expected.

**Comment by tomwtsn** [comment]
It now behaves as expected, able to load the JPEG and BMP images without a problem; thanks 👍
