### ISSUE TITLE
Error while saving an image

### ISSUE THREAD

**Issue by ZinoviyW** [birogeri/kspace-explorer#6]
On Ubuntu 22.04, saving an image creates "Aborted (core dumped)" error while running with     python kspace.py --log.

**Comment by ZinoviyW** [comment]
Error log here:
https://gist.github.com/ZinoviyW/787d8958c95c102f0cabb566d0a9313b

**Comment by birogeri** [comment]
I have updated the save function (https://github.com/birogeri/kspace-explorer/commit/08d83dd7c9e696e3a7ee02dd38bc75a5ecb36065).
Please [re-download](https://github.com/birogeri/kspace-explorer/archive/master.zip) K-space Explorer and check if it works.
I have also added the option to save as a `.jpg` file, if `.png` still does not work on your system

**Comment by ZinoviyW** [comment]
> I have updated the save function ([08d83dd](https://github.com/birogeri/kspace-explorer/commit/08d83dd7c9e696e3a7ee02dd38bc75a5ecb36065)). Please [re-download](https://github.com/birogeri/kspace-explorer/archive/master.zip) K-space Explorer and check if it works. I have also added the option to save as a `.jpg` file, if `.png` still does not work on your system

Thanks a lot, it works. Closing the issue!
